Wa API 테스트 프로그램 작성
yymin1022/Wa_API pull request #121
Opened 2023-11-27 06:07 UTC by kimch0612

## Summary
- Wa API를 테스트할 수 있는 코드를 추가했습니다.
## Description
- 이번에 추가한 코드는 다음과 같습니다.
  i. apitest(direct).py // message.py 파일에 direct로 접근해서 응답 Message를 return 받습니다.
  ii. apitest(flask).py // Wa API가 local에서 실제로 실행되고있는 상태에서 requests로 테스트 Message를 보내고, 응답을 return 받습니다.

- 각 코드의 설명입니다.

```python
# apitest(direct).py
# 단순히 Message의 Return값을 확인하는 용도로 사용하기에 적합함
import message
import os
import json

inputMessage = input("테스트 할 Message를 입력하세요: ") # 테스트할 Message를 입력받습니다.
replyMessage = message.getReplyMessage(inputMessage, "Test_Room1", "Test_Sender1") 
# message.py 파일 내에 있는 getReplyMessage 함수를 호출하고, return 받은 값을 replyMessage에 저장합니다.

if replyMessage == "":
    replyMessage = "None WA Bot Message Found"
# 문자열이 비어있는 경우 즉, Wa Bot이 응답할 message가 아닌 경우 replyMessage의 문자열을 위와 같이 설정합니다.
elif "\\m" in replyMessage:
    replyMessage = replyMessage.replace("\\m", "\n")
# 끊어보내는 문자가 존재하는 경우, 줄바꿈으로 바꿔서 출력합니다.

print(replyMessage)
```

```python
# apitest(flask).py
# data.json과 한 쌍임
# room이나 sender의 값에 따라 message가 달라지는 기능을 테스트하기에 적합함
import requests
import json

def post():
    url = "http://localhost/getMessage" # Message를 보낼 URL 정의
    json_data = { # 보낼 Message를 정의
        "msg": "와!",
        "room": "아 1집가고싶다",
        "sender": "Changhwan"
    }
    response = requests.post(url, json=json_data) # post 형식으로 requests 전송
    with open('./data.json', 'w', encoding='utf-8') as f:
        json.dump(response.json(), f, ensure_ascii=False, indent=4) # 받은 응답을 data.json에 저장

post()
```

```json
"__comment__": "data.json"

{
    "DATA": {
        "msg": "샌즈!\\m아시는구나!\\m이거 겁.나.어.렵.습.니.다.",
        "room": "아 1집가고싶다",
        "sender": "Changhwan"
    },
    "RESULT": {
        "RESULT_CODE": 0,
        "RESULT_MSG": "RESULT OK"
    }
}
```

2024-02-01 08:23 UTC, yymin1022 requested changes
..상당히 오래된 PR이 밀려있었네요.
몇가지 개선사항이 보여서 코멘트 남겼습니다!

2024-02-01 08:23 UTC, yymin1022 commented on apitest(flask).py
> +    with open('./data.json', 'w', encoding='utf-8') as f:
이부분에서 파일을 생성하고, 해당 파일에 기록하게 한 이유가 있을까요?
`response.json()` 내용을 곧바로 print 하도록 개선하면 좋을 것 같습니다.

추가로, `post()` 함수를 별도로 분리하지 않고 곧바로 코드로 동작하도록 해도 좋을 것 같네요.

2024-03-05 03:21 UTC, kimch0612 commented
수정했습니다

2024-03-05 05:30 UTC, kimch0612 commented
소해 관련해서 기능 몇개를 추가로 수정했습니다

2024-03-05 06:57 UTC, yymin1022 approved these changes
ㅋㅋ굿

2024-03-05 06:57 UTC, merged