와부자
yymin1022/Wa_API pull request #58
Opened 2023-03-07 14:37 UTC by kimch0612

개부자

2023-03-07 17:21 UTC, yymin1022 requested changes

2023-03-07 17:21 UTC, yymin1022 commented on message.py
> +    elif "으.." in message:
이건 조금 그러니 지워주십쇼~

2023-03-07 20:00 UTC, kimch0612 commented
입맛이 까다로우시네요 ㅡㅡ

2023-03-08 04:47 UTC, yymin1022 approved these changes
와 개부자

2023-03-08 04:47 UTC, merged