거북이 메시지 분리
yymin1022/Wa_API pull request #88
Opened 2023-07-06 10:39 UTC by noridev

## Summary
- 거북이를 호출하면 표시되는 메시지를 분리합니다.

## Description
- 몸통박치기와 물대포 메시지를 2개로 표시되도록 분리

2023-07-06 11:11 UTC, yymin1022 requested changes
개선사항 확인 부탁드립니다.

2023-07-06 11:11 UTC, yymin1022 commented on message.py
> +    randInt = random.randrange(0, 3)
`randInt` 값이 0인 경우에는 `ggobugiInt`가 필요하지 않은데,
`randInt` 값이 0이면 바로 return 하고,
그렇지 않은 경우에만 `ggobugiInt = random.randrange(0, 2)` 구문 이후 과정을 수행하면 어떨까요?

2023-07-07 07:14 UTC, noridev commented on message.py
> +    randInt = random.randrange(0, 3)
변경 완료했습니다

2023-07-07 08:22 UTC, yymin1022 requested changes
수정사항 확인 부탁드립니다.

2023-07-07 08:22 UTC, yymin1022 commented on message.py
> +    if randInt == 1:
`randInt == 2`인 경우에는 하단 548줄에서 `ggobugiMessage`가 정의되지 않은 상태로 호출되는 문제가 있습니다.

2023-07-07 08:29 UTC, yymin1022 approved these changes
고생하셨습니다.

2023-07-07 08:29 UTC, merged