날씨 수정 허준구
yymin1022/Wa_API pull request #96
Opened 2023-08-23 07:54 UTC by lmkhkm

날씨를 수정했다 이말이야

2023-08-23 08:42 UTC, yymin1022 requested changes
문자열 사이 개행을 넣는 등, 조금 더 가독성 개선이 있으면 좋을 것 같습니다.
추가로, Pull-Request 작성 시 템플릿 양식에 맞추어 작성 부탁드리겠습니다.

2023-08-23 09:05 UTC, lmkhkm commented
## Summary
- Modify weather data display

## Description
- The weather data display has been modified.
Here's the code.

```python
def messageWeather():

    weatherAPIUrl = "https://api.openweathermap.org/data/2.5/weather?id=1835847&appid=ea9e5f8d8e4aa2c798f8eb78f361d1b4"

    requestSession = requests.Session()
    requestSession.mount(weatherAPIUrl, DESAdapter())
    text = requestSession.get(weatherAPIUrl)
    text = text.text
    jsonData = json.loads(text)
    
    strMessage = "현재온도: " + str((jsonData["main"]["temp"])) +"K" + " 구름: " + str((jsonData["clouds"]["all"]))

    strMessage += "\n현재 날씨는 " + str((jsonData["weather"]["description"]))
    return strMessage
```


Modified part
```python
strMessage = "현재온도: " + str((jsonData["main"]["temp"])) +"K" + " 구름: " + str((jsonData["clouds"]["all"]))

strMessage += "\n현재 날씨는 " + str((jsonData["weather"]["description"]))
```

- How to use
Input "!날씨"

- Response
현재온도: 000K 구름:000
현재 날씨는 "Weather description"

2023-08-23 09:12 UTC, Splo2t commented
현재온도: 297.03K구름: 100 
로 출력이 예상됩니다. 

K와 구름 사이에 띄어쓰기 문자 추가하는게 어떤지 제안드립니다.

2023-08-23 09:14 UTC, yymin1022 commented
@Splo2t 띄어쓰기는 있긴 하네요. 문자열 +로 붙일 때 뒤쪽 구름 키워드 앞에 공백이 있어요
근데 이거 개행으로 하면 더 좋을 것 같은데..
그리고 +로 붙이기보다도 formatting 쓰면 어떨지요

2023-08-23 09:16 UTC, Splo2t commented on message.py
> +    strMessage = "현재온도: " + str((jsonData["main"]["temp"])) +"K" + " 구름: " + str((jsonData["clouds"]["all"]))
strMessage = "현재온도: " + str((jsonData["main"]["temp"])) +"K \\\n" + " 구름: " + str((jsonData["clouds"]["all"]))

위 코드로 수정이 좋아보입니다.

2023-08-23 09:16 UTC, Splo2t commented on message.py
> +    strMessage += "\n현재 날씨는 " + str((jsonData["weather"]["description"]))
개행문자는 \\\n 입니다.

2023-08-23 09:17 UTC, Splo2t commented
@yymin1022 띄어쓰기와 개행 관련하여 코드 리뷰 남겼습니다.

2023-08-25 14:46 UTC, lmkhkm commented on message.py
> +    strMessage += "\n현재 날씨는 " + str((jsonData["weather"]["description"]))
포매팅으로 바꾸고 개행 수정하겠습니다

2023-08-25 14:51 UTC, lmkhkm commented
## Summary
- Modify weather data display

## Description
- The weather data display has been modified.
Here's the code.

```python
def messageWeather():

    weatherAPIUrl = "https://api.openweathermap.org/data/2.5/weather?id=1835847&appid=ea9e5f8d8e4aa2c798f8eb78f361d1b4"

    requestSession = requests.Session()
    requestSession.mount(weatherAPIUrl, DESAdapter())
    text = requestSession.get(weatherAPIUrl)
    text = text.text
    jsonData = json.loads(text)
    
    strMessage = "현재온도: " + str((jsonData["main"]["temp"])) +"K" + " 구름: " + str((jsonData["clouds"]["all"]))

    strMessage += "\n현재 날씨는 " + str((jsonData["weather"]["description"]))
    return strMessage
```


Modified part
```python
strMessage = "현재온도: {}\\n구름: {}\\n현재 날씨는 {}".format(str((jsonData["main"]["temp"])), str((jsonData["clouds"]["all"])), str((jsonData["weather"]["description"])))
```

- How to use
Input "!날씨"

- Response
현재온도: 000K 구름:000
현재 날씨는 "Weather description"

2023-08-25 14:51 UTC, closed without merging